name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r addon/requirements.txt -r addon/requirements-dev.txt
      - name: Run pytest
        run: |
          cd addon
          pytest -q
